---

- name: "Get Runner Token"
  ansible.builtin.uri:
    url: "{{ github_runner_api_url }}"
    method: POST
    headers:
      Accept: "application/vnd.github+json"
      Authorization: "Bearer {{ github_token }}"
      X-GitHub-Api-Version: "2022-11-28"
    status_code: 201
  register: runner_token

- name: "Get latest version of Github Runner"
  ansible.builtin.uri:
    url: "https://api.github.com/repos/actions/runner/releases/latest"
    method: "GET"
    status_code: 200
    body_format: json
  register: github_runner_version_info

- name: Set value for github os
  ansible.builtin.set_fact:
    ansible_system_lower: "{{ ansible_system | lower }}"

- name: "Set facts to determine correct github runner tar.gz"
  ansible.builtin.set_fact:
    ghr_os: "{{ github_runner_os[ansible_system_lower] }}"
    ghr_arch: "{{ github_runner_arch[ansible_machine] }}"
    ghr_version: "{{ github_runner_version | default(github_runner_version_info.json.tag_name, true) }}"

- name: Set facts to build github runner download URL
  ansible.builtin.set_fact:
    github_runner_package: "actions-runner-{{ ghr_os }}-{{ ghr_arch }}-{{ ghr_version | regex_replace('v') }}.tar.gz"

- name: "Install Github Runner"
  become: false
  ansible.builtin.unarchive:
    src: "https://github.com/actions/runner/releases/download/{{ ghr_version }}/{{ github_runner_package }}"
    dest: "{{ github_runner_install_dir }}"
    mode: "u+x,g+x"
    remote_src: true
